modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="TABP Team, All rights reserved"
[[mods]] #mandatory
modId="apiviewer" #mandatory
version="${file.jarVersion}" #mandatory
displayName="API Viewer" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks to HTMLChannel for object dessort helping" #optional
authors="Thana" #optional
description='''
Utilities for SkyBlock, for viewing others API or yourself API.
By: Thana, HTMLChannel
'''
[[dependencies.apiviewer]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.apiviewer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
